apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 413149869599.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 413149869599.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 5d1e714e
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
